### ISSUE TITLE
D3: Using parentheses in interface members wraps it arguments in tuples

### ISSUE THREAD

**Issue by maestrow** [fable-compiler/fable-graphics#12]
In Fable.Import.D3.fs many arguments of abstract members are in brackets, like so:
```
type Zoom<'Datum> =
  abstract scaleExtent: unit -> float * float
  abstract scaleExtent: extent: (float * float) -> Zoom<'Datum>
```
The ways to call method `scaleExtent` is: 
1. `let a = 1., 1.`</br>`D3.Behavior.Globals.zoom().scaleExtent(a)`
2. `let (1., 1.) |> D3.Behavior.Globals.zoom().scaleExtent`
3. `D3.Behavior.Globals.zoom().scaleExtent ((1.,1.))`

If you try `D3.Behavior.Globals.zoom().scaleExtent(1., 1)` you get exception : "scaleExtent does not take two arguments".  That is because (float * float) type compiled as a Tuple in IL. Better way is to define arguments in interfaces without brackets: `abstract scaleExtent: float * float -> Zoom<'Datum>`. So now I can write: `D3.Behavior.Globals.zoom().scaleExtent(1., 1.)`. 

I suppose that Fable.Import.D3.fs generated by some script? So it makes no sense to make changes in Fable.Import.D3.fs directly, am I right?

**Comment by MangelMaxime** [comment]
Hello @maestrow , you are right we are generally generating the binding with a script. But then we tweak it by hand as the binding can be sometime difficult.

Not a lot of people use D3 with Fable so from my point of view you can create a PR and @alfonsogarciacaro will see if it make sense. :)

**Comment by alfonsogarciacaro** [comment]
Hi @maestrow! Sorry, I wasn't listening this repo so I didn't see the notification. Thanks @MangelMaxime for the mention.

The tuples are intended as d3 is one of the few JS libraries that accepts them. If you don't use a tuple it won't work. Please check the [Typescript declaration for `scalaeExtent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8a308e57a7617afec51543c5945f131356e5f7ec/d3/v3/index.d.ts#L1918).

> About the binding generation, yes it's made automatically with ts2fable but there's usually also some manual editing later.

**Comment by maestrow** [comment]
Thanks for your reply, guys. I'm already try [ts2fable](https://github.com/fable-compiler/Fable/tree/master/src/ts2fable) tool and found Type Script Interfaces Definition to version 4 of D3 [here](https://github.com/tomwanzek/d3-v4-definitelytyped) and try to generate F# binding with ts2fable. And it produced only small part of its TS-source. So my next options are:

1. Create D3 bindings mannually. Pros: I can get clean code with convenient chain methods (to call like a |> b |> c). Cons: routine.
2. Dive deep in TypeScript AST and F# compiler Service to make ts2fable produce code more close to original. But its too long road :)
3. Try Virtual Dom and fable-elmish to replace functionality that I want from D3.

So now I'm trying fable-elmish.

**Comment by MangelMaxime** [comment]
I'm closing this issue.
Please feel free to re-open if needed.
