### ISSUE TITLE
Bump to Pixi 4.x

### ISSUE THREAD

**Issue by realvictorprm** [fable-compiler/fable-graphics#14]
We should track the progress for Pixi 4.x

**Comment by realvictorprm** [comment]
I've started with automatic generated ones here
https://github.com/realvictorprm/fspixi

**Comment by realvictorprm** [comment]
@MangelMaxime what about posting your current binding here?

**Comment by MangelMaxime** [comment]
My bindings isn't complete for Pixi 4.x so it's would lead to problem for user ATM

**Comment by realvictorprm** [comment]
Do we have tests in here?
if not we must introduce them with your binding to see the edge cases.

**Comment by MangelMaxime** [comment]
No we don't have test in the repo.

But we have samples. Also, the edge case are not the one explored into the samples as they are still really simply.

**Comment by realvictorprm** [comment]
Hate me if I suggest tests but though it was a hard lesson, tests are useful. I'll introduce some tests for PIXI

**Comment by MangelMaxime** [comment]
Sure if you can add test would be appreciate :)

**Comment by whitetigle** [comment]
@realvictorprm what do you mean by tests? [This kind of tests?](https://github.com/pixijs/pixi.js/blob/dev/test/renders/tests/graphics-rect.js)

**Comment by MangelMaxime** [comment]
That's the question I was aking myself @whitetigle after all.

**Comment by whitetigle** [comment]
That's exactly what I was thinking about @MangelMaxime! 😆

**Comment by whitetigle** [comment]
Hi @realvictorprm. I've got a simple question for you: are your bindings ready to use and so can we update ours with yours? Or do we need to do it?
I'm asking you since I'm going to start working on this topic in the next days.
Thanks!

**Comment by realvictorprm** [comment]
Hey :)

Unfortunately they aren't, I didn't spend time on them again because I had
difficulties with understanding how it's done correctly.

Am 27.09.2017 10:21 AM schrieb "Whitetigle" <notifications@github.com>:

Hi @realvictorprm <https://github.com/realvictorprm>. I've got a simple
question for you: are your bindings ready to use and so can we update ours
with yours? Or do we need to update ours.
I'm asking you since I'm going to start working on this topic in the next
days.
Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/fable-graphics/issues/14#issuecomment-332446998>,
or mute the thread

**Comment by whitetigle** [comment]
ok! Thanks @realvictorprm! I'm going to start working on this right now then. Will ping back here when I get something working.

**Comment by whitetigle** [comment]
Hi! 

New repo for the pixi bindings will be in [fable-import](https://github.com/fable-compiler/fable-import). I will post prod ready bindings there.

Meanwhile, a first working version of the bindings can be found [here](https://github.com/fable-compiler/samples-pixi/blob/master/src/Fable.Import.Pixi.fs) and all the basic samples have been upgraded to pixi v4.5.5 and to the new pixi architecture (mostly using Application and Ticker now)

You can find the source [here](https://github.com/fable-compiler/samples-pixi/tree/master/src). 

I will go on porting the other samples. But as of now, I think we should be ok with most current usages.
 
Next discussions will take place in [sample-pixi](https://github.com/fable-compiler/samples-pixi) repo from now on.

Have fun!
![image](https://user-images.githubusercontent.com/883207/31015798-36ddcd72-a522-11e7-96e4-50b9dd8f92b8.png)
