### ISSUE TITLE
Wrong repo location in npmjs.org

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-graphics#8]
The repo location for:

- [fable-import-d3](https://www.npmjs.com/package/fable-import-d3)
- [fable-import-dc](https://www.npmjs.com/package/fable-import-dc)
- [fable-import-three](https://www.npmjs.com/package/fable-import-three)

are not pointed to *fable-graphics*.

Also, there is a repo `https://www.npmjs.com/package/fable-import-phaser` not affiliated to Fable-compiler. I don't know if this is known, because there is 2 repos for *fable-import-phaser* on github. (fable-graphic + [this one](https://github.com/heimeshoff/fable-import-phaser))

Ping @alfonsogarciacaro  :)

**Comment by alfonsogarciacaro** [comment]
Now that Fable 0.7 can reference assemblies and Rollup will remove the unnecessary parts, I think it may be more convenient for maintainers and users to merge several packages (as happened with `fable-react`, though I'm aware there're also downsides to this approach). We could do the same with `fable-graphics`. What do you think @MangelMaxime?

**Comment by MangelMaxime** [comment]
This is can be a good idea and I like it. We should provide the `fable-graphics` as a **dll**.

We need to be sure that Rollup + Fable will only include the needed part. Not that I am not confident in your work 😀 but this is for me a requirements and I never really tested it even for `0.10.0-alpha-1 of fable-arch`.

Also, one downsides will be users can be confused by this approaches and have difficulties finding their bindings. To solve this, we could maintain a table with the import name and where to find the binding. Or a mimi web app, where you can search for your libs. 
*Probably a dream but if some interest show in this proposition, I could take it in charge*

Table sample:

<table>
  <tr>
    <th>Libraries</th>
    <th>Binding location</th>
  </tr>
  <tr>
    <td>D3</td>
    <td rowspan="4">fable-graphics</td>
  </tr>
  <tr>
    <td>DC</td>
  </tr>
  <tr>
    <td>PIXI</td>
  </tr>
  <tr>
    <td>Phaser</td>
  </tr>
  <tr>
    <td>Fetch</td>
    <td rowspan="2">fable-powerpack</td>
  </tr>
  <tr>
    <td>Promise</td>
  </tr>
</table>

In the end, this is more or less what we started to do with `fable-powerpack` (Fetch, Promise, IndexedDB).

**Comment by alfonsogarciacaro** [comment]
Sorry for the late response! As the ecosystem is moving very fast, it may be a bit difficult to keep a table like that up-to-date, but if you take care of that I've absolutely no objections :wink: Would you want to put it in Fable's website?

**Comment by MangelMaxime** [comment]
Sure :)

Where should we add it ? As a new docs topic ?
Or at the end of the (Interacting page)[http://fable.io/docs/interacting.html] ?

I think having it at the end the interacting page is not optimal because it's not easily accessible. What is your opinion ?

**Comment by alfonsogarciacaro** [comment]
Yeah, probably a new doc entry would make sense. Something similar to the .NET compatibility page could work :)
